    function showPassword() {
      var x = document.getElementById("myInput");
      if (x.type === "password") {
        x.type = "text";
      } else {
        x.type = "password";
      }
    }

const form = document.getElementById("botForm");
const submitBtn = document.getElementById("submitBtn");
const codeBlock = document.getElementById("codeBlock");

let step = 1;

submitBtn.addEventListener("click", () => {
  if (step === 1) {
    submitBtn.innerHTML = "Confirm Values.<br>Click Again to Generate Code.";
    step = 2;
  } else {
    const formData = Object.fromEntries(new FormData(form).entries());
    document.getElementById("submitBtn").style.display = "none";
    localStorage.setItem("redditBotConfig", JSON.stringify(formData));

    const subs = formData.subreddits.split(",").map(s => s.trim()).filter(Boolean);
    const keywords = formData.keywords.split(",").map(k => `'${k.trim()}'`).filter(Boolean); // Build template

    const template = `

import praw
import os
from time import sleep

userAgent = '${formData.userAgent}'
clientId = '${formData.clientId}'
secret = '${formData.secret}'
username = '${formData.username}'
password = '${formData.password}'

reddit = praw.Reddit(
user_agent=userAgent,
client_id=clientId,
client_secret=secret,
username=username,
password=password,
)

subreddits = ["${subs.join('", "')}"]

content = """${formData.content}"""

keywords = [${keywords.join(", ")}]

resultsCount = 0

for sub in subreddits:
subreddit = reddit.subreddit(sub)
# Check posts
for submission in subreddit.hot(limit=20):
text = (submission.title + " " + submission.selftext).lower()
if any(keyword.lower() in text for keyword in keywords):
if submission.author and submission.author.name.lower() == username.lower():
continue
print("Bot replying to post: ")
print("Title: ", submission.title)
print("Text: ", submission.selftext)
print("----------------------------")
print(content, "This was generated by a bot!")
print()
try:
submission.reply(content)
resultsCount += 1
sleep(60)
except Exception as e:
print("Error replying to post: ", e)
# Check comments
submission.comments.replace_more(limit=0)
for comment in submission.comments.list():
if any(keyword.lower() in comment.body.lower() for keyword in keywords):
print("Bot replying to comment: ")
print("Comment: ", comment.body)
print("----------------------------")
try:
comment.reply(content)
resultsCount += 1
sleep(120)
except Exception as e:
print("Error replying to comment: ", e)

if resultsCount == 0:
print()
print("Sorry. I didn't find any posts or comments with those keywords.")
`;

// Show code
codeBlock.style.display = "block";
codeBlock.textContent = template;
}
});

        var modal = document.getElementById("myModal");
        var btn = document.getElementById("modal-btn");
        var span = document.getElementsByClassName("close")[0];

        btn.onclick = function () {modal.style.display = "block"};

        span.onclick = function () {modal.style.display = "none"};

        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        };


        var modal2 = document.getElementById("myModal2");
        var btn2 = document.getElementById("modal2-btn");
        var span = document.getElementsByClassName("close2")[0];

        btn2.onclick = function () {modal2.style.display = "block"};

        span.onclick = function () {modal2.style.display = "none"};
        window.onclick = function (event) {
            if (event.target == modal2) {
                modal2.style.display = "none";
            }
        };

