 <script>
function showPassword() {
  var x = document.getElementById("myInput");
  if (x.type === "password") {
    x.type = "text";
  } else {
    x.type = "password";
  }
}
</script>
   
<script>
    const form = document.getElementById("botForm");
    const submitBtn = document.getElementById("submitBtn");
    const codeBlock = document.getElementById("codeBlock");

    let step = 1;

submitBtn.addEventListener("click", () => {
    if (step === 1) {
        submitBtn.textContent = "Confirm Values";
        step = 2;
    } else {
        const formData = Object.fromEntries(new FormData(form).entries());
        document.getElementById("submitBtn").style.display = "none";

        // Save to localStorage
        localStorage.setItem("redditBotConfig", JSON.stringify(formData));

        // Process subreddits & keywords
        const subs = formData.subreddits.split(",").map(s => s.trim()).filter(Boolean);
        const keywords = formData.keywords.split(",").map(k => `'${k.trim()}'`).filter(Boolean);

        // Build template
        const template = `
userAgent = '${formData.userAgent}'
clientId = '${formData.clientId}'
secret = '${formData.secret}'
username = '${formData.username}'
password = '${formData.password}'

reddit = praw.Reddit(
    user_agent=userAgent,
    client_id=clientId,
    client_secret=secret,
    username=username,
    password=password,
)

subreddits = ["${subs.join('", "')}"]

content = """${formData.content}"""

keywords = {${keywords.join(", ")}}

resultsCount = 0

for sub in subreddits:
    subreddit = reddit.subreddit(sub)
    # Check posts
    for submission in subreddit.hot(limit=20):
        text = (submission.title + " " + submission.selftext).lower()
        if any(keyword.lower() in text for keyword in keywords):
            if submission.author and submission.author.name.lower() == username.lower():
                continue
            print("Bot replying to post: ")
            print("Title: ", submission.title)
            print("Text: ", submission.selftext)
            print("----------------------------")
            print(content, "This was generated by a bot!")
            print()
            try:
                submission.reply(content)
                resultsCount += 1
                sleep(60)
            except Exception as e:
                print("Error replying to post: ", e)
        # Check comments
        submission.comments.replace_more(limit=0)
        for comment in submission.comments.list():
            if any(keyword.lower() in comment.body.lower() for keyword in keywords):
                print("Bot replying to comment: ")
                print("Comment: ", comment.body)
                print("----------------------------")
                try:
                    comment.reply(content)
                    resultsCount += 1
                    sleep(120)
                except Exception as e:
                    print("Error replying to comment: ", e)

if resultsCount == 0:
    print()
    print("Sorry. I didn't find any posts or comments with those keywords.")
        `;

        // Show code
        codeBlock.style.display = "block";
        codeBlock.textContent = template;
}
    });
</script>

<script>
// Get the modal
var modal = document.getElementById("myModal");

// Get the button that opens the modal
var btn = document.getElementById("modalBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 
btn.onclick = function() {
modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
if (event.target == modal) {
    modal.style.display = "none";
}
}
</script>
